export const PHASES = {

    ALL_VIEW_ROLE: 'ALL_VIEW_ROLE',

    NIGHT_ALL_SLEEP: 'NIGHT_ALL_SLEEP',

    NIGHT_SEER: 'NIGHT_SEER',

    NIGHT_GUARD: 'NIGHT_GUARD',

    NIGHT_SILENCED: 'NIGHT_SILENCED',

    NIGHT_WOLF: 'NIGHT_WOLF',

    NIGHT_WITCH_SAVE: 'NIGHT_WITCH_SAVE',

    NIGHT_WITCH_KILL: 'NIGHT_WITCH_KILL',

    NIGHT_CURSED: 'NIGHT_CURSED',

    DAY_DISCUSSION: 'DAY_DISCUSSION',

    END: 'END'
};