module.exports = {
    //
    CONNECT_ROOM: 'CONNECT_ROOM',
    LEAVE_ROOM: 'LEAVE_ROOM',
    START_NEW_GAME: 'START_NEW_GAME',
    START_NIGHT: "START_NIGHT",
    SEER_DONE: "SEER_DONE",
    BODYGUARD_DONE: "BODYGUARD_DONE",
    SILENCED_DONE: "SILENCED_DONE",
    WEREWOLF_VOTING: "WEREWOLF_VOTING",

    //
    ROOM_PLAYERS: "ROOM_PLAYERS",
    NEXT_GAME_FLOW: "NEXT_GAME_FLOW",

    //
    SOCKET_ERROR: 'SOCKET_ERROR'
};
