module.exports = {
    //
    CONNECT_ROOM: 'CONNECT_ROOM',
    LEAVE_ROOM: 'LEAVE_ROOM',
    START_NEW_GAME: 'START_NEW_GAME',
    BEGIN_GAME_FLOW: "BEGIN_GAME_FLOW",

    //
    ROOM_PLAYERS: "ROOM_PLAYERS",
    NEXT_GAME_FLOW: "NEXT_GAME_FLOW",

    //
    SOCKET_ERROR: 'SOCKET_ERROR'
};
