name: Auto Deploy to Hosting

on:
  push:
    branches:
      - backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          # Các biến này đã khớp với ảnh Secrets của bạn
          host: ${{ secrets.HOSTING_HOST }}
          username: ${{ secrets.HOSTING_USERNAME }}
          password: ${{ secrets.HOSTING_PASSWORD }}
          port: ${{ secrets.HOSTING_PORT }} # Hãy chắc chắn Secret này là số 22
          timeout: "60s"
          script: |
            # 1. Đi vào thư mục
            cd /home/anhdhnet/repositories/be/werewolf-game
            
            # 2. Pull code
            echo "Pulling code..."
            git pull origin backend
            
            # 3. Kích hoạt môi trường (Dùng biến HOSTING_USERNAME cho chuẩn)
            echo "Installing..."
            source /home/${{ secrets.HOSTING_USERNAME }}/nodevenv/repositories/be/werewolf-game/20/bin/activate
            npm install --production
            
            # 4. Restart server
            echo "Restarting..."
            mkdir -p tmp
            touch tmp/restart.txt
            
            # Sửa lỗi: Dùng đúng tên biến HOSTING_USERNAME
            pkill -u ${{ secrets.HOSTING_USERNAME }} node || true
            
            echo "DEPLOY THANH CONG!"